global:
  environment: uat
  namespace: ns-resim-uat
  imageRegistry: 009160046075.dkr.ecr.ap-northeast-1.amazonaws.com
  serviceAccountName: resim-irsa-service-account
  secretProviderClass: aws-secrets-uat
  secretName: resim-env-variables-secret
  kmsKeyArn: "arn:aws:kms:ap-northeast-1:009160046075:key/f0f919f4-867c-4f78-bcf4-19e2ea8f2e6a"
  awsRegion: eu-central-1
  initContainers:
    enabled: true
  tolerations:
    enabled: false

replicas: 1
hpa:
  enabled: false
pdb:
  enabled: false

image:
  repository: kai-voice-agent-uat
  tag: latest

name: kai-voice-agent
configMapName: notification-app-config

config: {}

service:
  name: kai-voice-agent-service
  port: 8081
  targetPort: 8081

metricsPort: 9090

resources:
  requests:
    memory: "256Mi"
    cpu: "125m"
  limits:
    memory: "512Mi"
    cpu: "250m"

probes:
  enabled: true
